name: Deploy to GitHub Pages

on:
  push:
    branches: 'cardsboard' # default branch

jobs:
  build_site:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: pnpm
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          pnpm run build
          echo '${{ secrets.CONFIG_JSON }}' > build/config.json

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4