name: Deploy to Server

on:
  push:
    branches: 
    - 'cardsboard' # default branch
    - 'deploy-server' # TODO: delete before merging

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: pnpm
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          pnpm run build
          echo '${{ secrets.CONFIG_JSON }}' > build/config.json

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/user
          chmod 600 ~/.ssh/user
          ssh-keyscan -p 22 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          sudo apt-get install sshpass
          ssh -i ~/.ssh/user ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ichbinhierrrrrrrrrr"
      
      - name: Deploy with rsync
        run: |
          rsync -az --delete \
            build/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/kanban-editor
